# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 12:59
from __future__ import unicode_literals

import db_repo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Objs',
            fields=[
                ('oid', db_repo.models.RealBinaryField(max_length=40, primary_key=True, serialize=False)),
                ('repo', models.CharField(db_index=True, max_length=64)),
                ('type', db_repo.models.TinyIntegerField(db_index=True)),
                ('size', models.BigIntegerField()),
                ('data', db_repo.models.CompressedBinaryField()),
            ],
            options={
                'db_table': 'objs',
            },
        ),
        migrations.CreateModel(
            name='Refs',
            fields=[
                ('ref', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('repo', models.CharField(db_index=True, max_length=64)),
                ('value', db_repo.models.RealBinaryField(db_index=True, max_length=40)),
            ],
            options={
                'db_table': 'refs',
            },
        ),
        migrations.AlterUniqueTogether(
            name='refs',
            unique_together=set([('ref', 'repo')]),
        ),
        migrations.AlterIndexTogether(
            name='refs',
            index_together=set([('ref', 'repo')]),
        ),
        migrations.AlterUniqueTogether(
            name='objs',
            unique_together=set([('oid', 'repo')]),
        ),
        migrations.AlterIndexTogether(
            name='objs',
            index_together=set([('oid', 'repo')]),
        ),
    ]
